name: CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}

      - run: yarn

      - run: yarn build
        env:
          CI: false # otherwise warnings are treated as errors

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: cache go
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-modbuild-${{ hashFiles('**/go.sum') }}

      - name: build backend
        run: |
          set -eux
          (cd execjs; CGO_ENABLED=1 go build -ldflags="-s -w")
          (cd initializer; go build -ldflags="-s -w")

      - name: deploy
        uses: docker://glassechidna/stackit
        with:
          args: stackit up --stack-name stepfn-dev --template cfn.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
